version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - EmaSuriano
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: image-size
    versions:
    - 0.9.4
    - 0.9.5
    - 0.9.7
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: "@narative/gatsby-theme-novela"
    versions:
    - 0.18.5
    - 0.18.6
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 2.12.0
  - dependency-name: "@types/line-reader"
    versions:
    - 0.0.32
