content:
  - name: posts
    label: Posts
    path: src/content/blog
    type: collection
    view:
      fields: [ title, publishedAt ]
    fields:
      - name: publishedAt
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: cover
        label: Cover
        type: string
      - name: summary
        label: Summary
        type: string 
      - name: body
        label: Body
        type: rich-text