[[redirects]]
  from="/resume"
  to="https://resume.emasuriano.com"

[[redirects]]
  from="/avatar"
  to="https://secure.gravatar.com/avatar/de8225213d7b8bc59895625735574f7d?s=2048"

[[redirects]]
  from="/art"
  to="https://art.emasuriano.com"