[build]
  publish = "public"
  command = "yarn build:incremental"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/talks/*"
  to = "https://talks.emasuriano.com/:splat"

[[redirects]]
  from="/resume"
  to="https://standardresume.co/r/emasuriano"

[[redirects]]
  from="/oss/*"
  to="https://oss.emasuriano.com/:splat"
