jobs:
  install:
    executor:
      name: node/default
      tag: 'latest'
    steps:
      - checkout
      - node/install-packages
  build:
    executor:
      name: node/default
    steps:
      - run: yarn build
  lint:
    executor:
      name: node/default
    steps:
      - run: yarn lint
  test-ci:
    executor:
      name: node/default
    steps:
      - run: yarn test:ci
version: 2.1
orbs:
  node: circleci/node@2.1.1
workflows:
  build:
    jobs:
      - install
      - build
        requires:
          - install
      - test-ci
        requires:
          - install
      - lint
        requires:
          - install
