jobs:
  install:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: node --version
      - node/install-packages
  build:
    executor:
      name: node/default
    steps:
      - run:
        command: yarn build
  lint:
    executor:
      name: node/default
    steps:
      - run:
        command: yarn lint
  test-ci:
    executor:
      name: node/default
    steps:
      - run:
        command: yarn test:ci
version: 2.1
orbs:
  node: circleci/node@2.1.1
workflows:
  build:
    jobs:
      - install
      - build
        requires:
            - install
      - test-ci
        requires:
            - install
      - lint
        requires:
            - install
