jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - run: yarn lint
  test-ci:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn test:ci
version: 2.1
orbs:
  node: circleci/node@2.1.1
workflows:
  build:
    jobs:
      - build
      - test-ci
