version: 2
jobs:
  build:
    docker:
      - image: cypress/base:12
        environment:
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn lint
      - run: yarn check-markdown
      - run:
          name: 'Run app'
          background: true
          command: yarn start
      - run: yarn e2e:run
