jobs:
  test-ci:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock
      - run: yarn build
      - run: yarn lint
      - run: yarn test:ci
version: 2.1
orbs:
  node: circleci/node@2.1.1
workflows:
  build:
    jobs:
      - test-ci
