name: Manual workflow

on:
  push:
    branches: master
  pull_request:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Manual deploy
        uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile
      - run: yarn create-summary
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Summary
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.2
        with:
          token: ${{secrets.GH_TOKEN}}
          repository: EmaSuriano/EmaSuriano
          event-type: my-event
