name: Update Summary

on:
  push:
    branches:
      - master

jobs:
  update-summary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - run: yarn install --frozen-lockfile
      - run: yarn create-summary
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Summary
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.2
        with:
          token: ${{secrets.GH_TOKEN}}
          repository: EmaSuriano/EmaSuriano
          event-type: my-event
